apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: group2
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Adjust if your frontend container listens on a different port
  type: LoadBalancer
