FROM node:22.11.0-alpine
WORKDIR /app
COPY . .

# Define build arguments
ARG REACT_APP_API_URL_IDEA
ARG REACT_APP_API_URL_COMMENT
ARG REACT_APP_API_URL_USER
ARG REACT_APP_API_URL_MESSAGE

# Set environment variables for the build
ENV REACT_APP_API_URL_IDEA=$REACT_APP_API_URL_IDEA
ENV REACT_APP_API_URL_COMMENT=$REACT_APP_API_URL_COMMENT
ENV REACT_APP_API_URL_USER=$REACT_APP_API_URL_USER
ENV REACT_APP_API_URL_MESSAGE=$REACT_APP_API_URL_MESSAGE

RUN npm install
RUN npm run build
EXPOSE ${FRONTEND_PORT}
CMD ["npm", "start"]